"""Shared palette and layout measurements: geometry in inches, type in points."""

PAGE_W = 10.0
PAGE_H = 13.33
LEFT_W = 3.45
GAP = 0.28
RIGHT_X = LEFT_W + GAP
RIGHT_W = PAGE_W - RIGHT_X - 0.22
# The hero meets the blue panel and reaches the top and right page edges.
HERO_X = LEFT_W
HERO_W = PAGE_W - LEFT_W
HERO_H = 7.42
C = {
    "blue": "6F97C5",
    "dark_blue": "07347A",
    "yellow": "F9B800",
    "yellow2": "FFC515",
    "ink": "1D2530",
    "muted": "5C6573",
    "pale": "F5F1E6",
    "line": "0D3D85",
    "white": "FFFFFF",
    "cream": "FBF8F0",
    "grey": "E8E8E8",
    "border": "D8D8D8",
    "accent": "0070C0",
}

# Page 1 header block. The title sits lower and wider than the panel's centre,
# so the panel ends above the servings pill rather than behind it.
HEADER_PANEL_H = 3.82
HEADER_TIME_ICON_X = 1.19
HEADER_TIME_TEXT_X = 1.39
HEADER_TIME_TEXT_W = 0.85
HEADER_POT_X = 1.57
HEADER_POT_Y = 1.25
TITLE_X = 0.25
TITLE_Y = 1.45
TITLE_W = 3.04
TITLE_H = 1.61
SUBTITLE_Y = 3.03
SUBTITLE_W = 2.84
SUBTITLE_H = 0.64
SERVINGS_Y = 3.95
SERVINGS_TEXT_OFFSET = 0.08

# Overview right column.
CALLOUT_Y = 7.66
DESCRIPTION_FONT_SIZE = 9.0
DESCRIPTION_H = 0.42
MENU_TITLE_FONT_SIZE = 10.5
MENU_BLURB_W = 1.90
MENU_BLURB_H = 0.34
MENU_PICTURE_W = 2.33
MENU_PICTURE_H = 0.84
MENU_LABEL_OFFSET = 0.35

# Closing panels on the last steps page.
VARIATIONS_PANEL_OFFSET = 0.30
VARIATIONS_PANEL_H = 1.35
VARIATIONS_TAB_W = 2.60
VARIATIONS_TAB_H = 0.36
VARIATIONS_SKETCH_X = 7.00
BANNER_TEXT_X = 0.46
BANNER_TEXT_W = 3.56
BANNER_FONT_SIZE = 20.0
HEAD_FONT = "Georgia"
BODY_FONT = "Aptos"
# Conservative mean character widths and line heights for fixed-size text.
CHAR_WIDTH_RATIO = 0.45
HEAD_CHAR_WIDTH_RATIO = 0.41
LINE_HEIGHT_RATIO = 1.22
POINTS_PER_INCH = 72.0

TITLE_FONT_SIZE = 36.0
TITLE_FONT_SIZE_LONG = 28.0
TITLE_LONG_THRESHOLD = 28
TIP_CHARS_PER_LINE = 92
TIP_LINE_HEIGHT = 0.26
TIP_VERTICAL_PADDING = 0.30
INGREDIENT_FONT_SIZE = 10.0
INGREDIENT_ROW_MAX_HEIGHT = 0.72
# Keep rows readable; additional ingredients go onto continuation pages.
INGREDIENT_ROW_MIN_HEIGHT = 0.46
INGREDIENT_PANEL_PADDING = 0.22
INGREDIENT_MAX_ROWS = 12
INGREDIENT_PANEL_TOP = 4.45
INGREDIENT_PANEL_MAX_BOTTOM = 12.42
STEP_IMAGE_WIDTH_FRACTION = 0.46
STEP_IMAGE_MIN_ASPECT = 1.05
CHEF_NOTE_FONT_SIZE = 11.5
VARIATIONS_GAP = 0.30
VARIATIONS_MIN_TOP = 8.30
VARIATIONS_MAX_TOP = 10.30
VARIATIONS_MIN_TOP_SHORT_PAGE = 6.40
VARIATIONS_TO_BANNER = 1.84
STEP_BLOCK_GAP = 0.24
STEP_BLOCK_MIN_HEIGHT = 2.60
# Bound expansion so photographs do not dominate short instruction pages.
STEP_BLOCK_MAX_SCALE = 1.85
STEP_BLOCK_COLUMN_SHARE = 0.58
STEPS_PAGE_BOTTOM = 12.60
STEPS_LAST_PAGE_BOTTOM = 8.90
STEP_TITLE_FONT_SIZE = 20.0
STEP_TITLE_BOX_HEIGHT = 0.62
BULLET_FONT_SIZE = 10.0
BULLET_LINE_HEIGHT = 0.56
WORDS_PER_BULLET_LINE = 6
BULLET_ROW_PADDING = 0.10
